name: shaders
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_shaders: ^0.1.0

  cupertino_icons: ^1.0.8
  go_router: ^14.6.2
  path: ^1.9.1
  shadcn_ui: ^0.28.1
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  image: ^4.5.4

  flutter_lints: ^5.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/shaders_text/
    - assets/screenshots/

  shaders:
    - shaders/crt_shader.frag
    - shaders/noise_overlay_shader.frag
    - shaders/noise_shader.frag
    - shaders/ntsc_shader.frag
    - shaders/rings_shader.frag
    - shaders/clearly_bug_shader.frag
    - shaders/ai_assistant.frag
    - shaders/branded_ai_assistant.frag
    - shaders/breathing_point.frag
    - shaders/distorted_motion.frag
    - shaders/plasma_xor.frag
    - shaders/sea.frag
    - shaders/flutter_xor.frag
